{
  "banks": [
    ["Abhyudaya Co-op Bank","http://www.abhyudaya.com"],
    ["Abu Dhabi Commercial Bank","http://www.adcb.com"],
    ["Ahmedabad Mercantile Co-op Bank","http://www.amco-bank.com"],
    ["Akola District Central Co-op Bank","http://akoladcc.com"],
    ["Akola Janata Commercial Co-op Bank","http://www.akolajanatabank.com"],
    ["Allahabad Bank","http://www.allahabadbank.com"],
    ["Almora Urban Co-op Bank","http://almoraurbanbank.com"],
    ["Andhra Bank","http://www.andhrabank.in"],
    ["Andhra pradesh State Co-Op Bank","http://www.apcob.org"],
    ["Andhra Pragathi Grameena Bank","http://www.apgb.co.in"],
    ["Apna Sahakari Bank","http://www.apnabank.co.in"],
    ["Australia and New Zealand Banking Group","http://www.anz.com"],
    ["Axis Bank","http://www.axisbank.com"],
    ["Bank of America","http://www.bankofamerica.com"],
    ["Bank of Bahrain and Kuwait","http://www.bbkonline.com"],
    ["Bank of Baroda","http://www.bankofbaroda.com"],
    ["Bank of Ceylon","http://www.boc.lk"],
    ["Bank of India","http://www.bankofindia.com"],
    ["Bank of Maharashtra","http://www.bankofmaharashtra.in"],
    ["Bank of Nova Scotia","http://www.scotiabank.com"],
    ["Bank of Tokyo Mitsubishi UFJ","http://www.bk.mufg.jp/global/globalnetwork/asiaoceania/#India"],
    ["Barclays Bank","http://www.barclays.in"],
    ["Bassein Catholic Co-op Bank","http://www.bccb.co.in"],
    ["Bharat Co-op Bank (Mumbai)","http://www.bharatbank.com"],
    ["BNP Paribas","http://www.bnpparibas.com"],
    ["Canara Bank","http://www.canarabank.com"],
    ["Capital Local Area Bank","http://www.capitalbank.co.in"],
    ["Catholic Syrian Bank","http://www.csb.co.in"],
    ["Central Bank of India","http://www.centralbankofindia.co.in"],
    ["China Trust Commercial Bank","http://www.chinatrustindia.com"],
    ["Citi Bank","http://www.citibank.com"],
    ["Citizen Credit Co-op Bank","http://www.citizencreditbank.com"],
    ["City Union Bank","http://www.cityunionbank.com"],
    ["Commonwealth Bank of Australia","http://www.commbank.co.in"],
    ["Corporation Bank","http://www.corpbank.com"],
    ["Cosmos Co-op Bank","http://www.cosmosbank.com"],
    ["Credit Agricole Corporate and Investment Bank","http://www.ca-cib.com"],
    ["Credit Suisse","http://www.credit-suisse.com"],
    ["Delhi State Co-op Bank","http://plus.google.com/107903992827578686784/about?hl=en"],
    ["Dena Bank","http://www.denabank.com"],
    ["Deposit Insurance and Credit Guarantee Corporation","http://www.dicgc.org.in"],
    ["Deutsche Bank","http://www.db.com"],
    ["Development Bank of Singapore (DBS)","http://www.dbs.com"],
    ["Development Credit Bank (DCB)","http://www.dcbbank.com"],
    ["Dhanlaxmi Bank","http://www.dhanbank.com"],
    ["Dombivli Nagari Sahakari Bank","http://www.dnsb.co.in"],
    ["Federal Bank","http://www.federalbank.co.in"],
    ["Firstrand Bank","http://firstrand.co.in"],
    ["Gadchiroli District Central Co-op Bank","http://www.gdccbank.com"],
    ["Gopinath Patil Parsik Janata Sahakari Bank","http://www.gpparsikbank.com"],
    ["Greater Bombay Co-op Bank","http://www.greaterbank.com"],
    ["Gujarat State Co-op Bank","http://www.gscbank.co.in"],
    ["Gurgaon Gramin Bank","http://plus.google.com/115047032409973911708/about?hl=en"],
    ["HDFC Bank","http://www.hdfcbank.com"],
    ["HSBC","http://www.hsbc.co.in"],
    ["ICICI Bank","http://www.icicibank.com"],
    ["IDBI Bank","http://www.idbi.com"],
    ["Indian Bank","http://www.indianbank.in"],
    ["Indian Overseas Bank (IOB)","http://www.iob.in"],
    ["Indonesia International Bank","http://www.bankbii.co.in"],
    ["Indusind Bank","http://www.indusind.com"],
    ["Industrial and Commercial Bank of China","http://www.icbc-ltd.com/icbcltd/en/"],
    ["ING Vysya Bank","http://www.ingvysyabank.com"],
    ["Jalgaon Janata Sahkari Bank (JJSB) Ltd","http://www.jjsbl.com"],
    ["Jalgaon Peoples Co-op Bank","http://www.jpcbank.com"],
    ["Jammu and Kashmir Bank","http://www.jkbank.net"],
    ["Janakalyan Sahakari Bank Ltd","http://www.jksbl.com"],
    ["Janaseva Sahakari Bank (Borivali)","http://janasevabank.in"],
    ["Janaseva Sahakari Bank (Pune)","http://janasevabankpune.net"],
    ["JP Morgan Chase Bank","http://www.jpmorgan.com"],
    ["Kallappanna Awade Ichalkaranji Janata Sahakari (KAIJS) Bank","http://www.ijsbank.com"],
    ["Kalupur Commercial Co-op Bank","http://www.kalupurbank.com"],
    ["Kalyan Janata Sahakari Bank","http://kalyanjanata.in"],
    ["Kangra Central Co-op Bank","http://www.kccb.in"],
    ["Kapole Co-op Bank","http://www.kapolbank.com"],
    ["Karad Urban Co-op Bank","http://www.karadurbanbank.com"],
    ["Karnataka Bank","http://www.karnatakabank.com"],
    ["Karnataka State Co-op Apex Bank","http://www.karnatakaapex.com"],
    ["Karnataka Vikas Grameena Bank","http://www.kvgbank.com"],
    ["Karur Vysya Bank (KVB)","http://www.kvb.co.in"],
    ["Kotak Mahindra Bank","http://www.kotak.com"],
    ["Kurmanchal Nagar Sahkari Bank","http://www.kurmanchalbank.com"],
    ["Lakshmi Vilas Bank (LVB)","http://www.lvbank.com"],
    ["Mahanagar Co-op Bank","http://www.mahanagarbank.com"],
    ["Maharashtra State Co-op Bank","http://www.mscbank.com"],
    ["Malabar Gramin Bank","http://keralagbank.com"],
    ["Mashreq Bank","http://www.mashreqbank.com"],
    ["Mizuho Co-op Bank","http://www.mizuhobank.com"],
    ["Mumbai District Central Co-op Bank","http://www.mumbaidistrictbank.com"],
    ["Municipal Co-op Bank (Mumbai)","http://www.municipalbankmumbai.com"],
    ["Nagar Urban Co-op Bank","http://plus.google.com/118254408225094337228/about?gl=in&amp;hl=en"],
    ["Nagpur Nagrik Sahakari Bank","http://www.nnsbank.co.in"],
    ["Nainital Bank","http://www.nainitalbank.co.in"],
    ["Nasik Merchants Co-op Bank","http://www.nasikonline.com"],
    ["National Australia Bank","http://nabasia.in"],
    ["New India Co-op Bank","http://www.newindiabank.in"],
    ["North Kanara GSB (NKGSB) Co-op Bank","http://www.nkgsb-bank.com"],
    ["Nutan Nagarik Sahakari Bank","http://www.nutanbank.com"],
    ["Oman International Bank","http://www.oib.co.om"],
    ["Oriental Bank of Commerce","http://www.obcindia.co.in"],
    ["Prathama Bank","http://www.prathamabank.org"],
    ["Prime Co-op Bank","http://primebankindia.com"],
    ["Punjab and Maharashtra Co-op Bank","http://www.pmcbank.com"],
    ["Punjab and Sind Bank","http://www.psbindia.com"],
    ["Punjab National Bank","http://www.pnbindia.in"],
    ["RABO Bank International","http://www.rabobank.com"],
    ["Rajaguru nagar Sahakari Bank","http://rajgurunagarbank.com"],
    ["Rajasthan State Co-op Bank","http://www.rscb.org.in"],
    ["Rajkot Nagarik Sahakari Bank","http://www.rnsbindia.com"],
    ["Ratnakar Bank","http://ratnakarbank.co.in"],
    ["Reserve Bank of India","http://www.rbi.org.in"],
    ["Royal Bank of Scotland","http://www.rbs.in"],
    ["Sahebrao Deshmukh Co-op Bank","http://sdcbankct.in"],
    ["Saraswat Co-op Bank","http://www.saraswatbank.com"],
    ["Sberbank of Russia","http://sberbank.ru"],
    ["Seva Vikas Co-op Bank","http://www.sevavikasbank.com"],
    ["Shamrao Vithal Co-op Bank","http://www.svcbank.com"],
    ["Shinhan Bank","http://www.shinhanbankindia.com"],
    ["Shri Chhatrapathi Rajarshi Shahu Urban Co-op Bank","http://www.shahubank.com"],
    ["Societe Generale","http://www.sgcib.com"],
    ["Solapur Janata Sahkari Bank","http://sjsbbank.com"],
    ["South Indian Bank","http://www.southindianbank.com"],
    ["Standard Chartered Bank","http://www.standardchartered.co.in"],
    ["State Bank of Bikaner and Jaipur","http://www.sbbjbank.com"],
    ["State Bank of Hyderabad","http://www.sbhyd.com"],
    ["State Bank of India (SBI)","http://www.sbi.co.in"],
    ["State Bank of Mauritius","http://www.sbmgroup.mu"],
    ["State Bank of Mysore","http://www.statebankofmysore.co.in"],
    ["State Bank of Patiala","http://www.sbp.co.in"],
    ["State Bank of Travancore (SBT)","http://www.statebankoftravancore.com"],
    ["Sumitomo Mitsui Banking Corporation","http://www.smbc.co.jp/global"],
    ["Surat District Co-op Bank","http://www.sudicobank.com"],
    ["Surat Peoples Co-op Bank","http://www.spcbl.in"],
    ["Sutex Co-op Bank","http://www.sutexbank.in"],
    ["Syndicate Bank","http://www.syndicatebank.in"],
    ["Tamilnad Mercantile Bank (TMB)","http://www.tmb.in"],
    ["Tamilnadu State Apex Co-op Bank","http://www.tnscbank.com"],
    ["Thane Bharat Sahakari Bank","http://www.thanebharatbank.com"],
    ["Thane District Central Co-op Bank","http://thanedistrictbank.com"],
    ["Thane Janata Sahakari Bank (TJSB)","http://www.thanejanata.co.in"],
    ["Tumkur Grain Merchants Co-op Bank","http://tgmcbank.com"],
    ["UCO Bank","http://www.ucobank.com"],
    ["Union Bank of India","http://www.unionbankofindia.co.in"],
    ["United Bank of India","http://www.unitedbankofindia.com"],
    ["United Overseas Bank","http://www.uobgroup.com/in"],
    ["Varachha Co-op Bank","http://www.varachhabank.com"],
    ["Vasai Vikas Sahakari Bank","http://vasaivikasbank.com"],
    ["Vijaya Bank","http://www.vijayabank.com"],
    ["Vishweshwar Sahakari Bank","http://vishweshwarbank.com"],
    ["West Bengal State Co-op Bank","http://www.wbscb.com"],
    ["Westpac Banking Corporation","http://http://www.westpac.com.au/about-westpac/global-locations/westpac-in-asia/india-website/"],
    ["Woori Bank","http://in.wooribank.com"],
    ["Yes Bank","http://www.yesbank.in"],
    ["Zila Sahkari Bank (Ghaziabad)","http://plus.google.com/115014569969060454496/about?gl=in&amp;hl=en"]
  ]
}
